version: '3'
networks:
  cecochat:
services:
  zookeeper:
    image: zookeeper:3.4.14
    container_name: cecochat-zookeeper
    hostname: zookeeper
    networks: &networks
      - cecochat
    ports:
      - "2181:2181"
    mem_limit: 256M
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - cecochat-zookeeper-data:/data
      - cecochat-zookeeper-datalog:/datalog
  kafka1:
    image: confluentinc/cp-kafka:5.5.3
    container_name: cecochat-kafka1
    hostname: kafka1
    networks: *networks
    ports:
      - "9091:9091"
    mem_limit: 512M
    environment: 
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
    volumes: 
      - cecochat-kafka1-data:/var/lib/kafka/data
    depends_on: 
      - zookeeper
  kafka2:
    image: confluentinc/cp-kafka:5.5.3
    container_name: cecochat-kafka2
    hostname: kafka2
    networks: *networks
    ports:
      - "9092:9092"
    mem_limit: 512M
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
    volumes: 
      - cecochat-kafka2-data:/var/lib/kafka/data
    depends_on:
      - zookeeper
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: cecochat-kafdrop
    restart: "no"
    networks: *networks
    ports: 
      - "9000:9000"
    mem_limit: 256M
    environment: 
      KAFKA_BROKERCONNECT: "kafka1:19091"
    depends_on: 
      - kafka1
      - kafka2
volumes:
  cecochat-zookeeper-data:
    external: true
  cecochat-zookeeper-datalog:
    external: true
  cecochat-kafka1-data:
    external: true
  cecochat-kafka2-data:
    external: true
