name: CI/CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore source/CecoChat.sln

    - name: Build
      run: dotnet build --no-restore source/CecoChat.sln

  analyze-code-quality:
    needs: build
    runs-on: windows-latest
    steps:

      - name: JDK 11 setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"cvetomir-todorov_CecoChat" /o:"cvetomirtodorov-cecochat" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build source/CecoChat.sln
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

  containerize:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Docker Hub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker setup
      uses: docker/setup-buildx-action@v1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Connect image
      uses: docker/build-push-action@v2
      with:
        file: containerize/Connect.Dockerfile
        context: ./source
        push: true
        tags: cvetomirtodorov/cecochat-connect:0.1

    - name: History image
      uses: docker/build-push-action@v2
      with:
        file: containerize/History.Dockerfile
        context: ./source
        push: true
        tags: cvetomirtodorov/cecochat-history:0.1

    - name: Materialize image
      uses: docker/build-push-action@v2
      with:
        file: containerize/Materialize.Dockerfile
        context: ./source
        push: true
        tags: cvetomirtodorov/cecochat-materialize:0.1

    - name: Messaging image
      uses: docker/build-push-action@v2
      with:
        file: containerize/Messaging.Dockerfile
        context: ./source
        push: true
        tags: cvetomirtodorov/cecochat-messaging:0.1

    - name: Profile image
      uses: docker/build-push-action@v2
      with:
        file: containerize/Profile.Dockerfile
        context: ./source
        push: true
        tags: cvetomirtodorov/cecochat-profile:0.1
